POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/90a54588-5c50-458f-bd9e-f8e861ada119/attendees
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br"
}

###

GET http://localhost:3333/events/90a54588-5c50-458f-bd9e-f8e861ada119

###

GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/711cbdd3-170f-4e4f-8cb0-6987ebcdf2b0/attendees?query=diego
